### ISSUE TITLE
Error reports

### ISSUE THREAD

**Issue by reisnerv** [davhin/ResponseOnsetTool#10]
Error reports while using [response.m](https://github.com/davhin/ResponseOnsetTool/files/625124/used_script.zip):

**1) for _MM_012_P04_06_, file _momap_pilot04_51_15_5_6_:**

"Attempted to access `data_sm(-9, :);` index must be a positive integer or logical.

Error in response (line 34)
   `if (data_sm(position,:) < mean(data_sm))`

Error in folder_response (line 35)
    `[resp, ons, mpeak, avgpeak, ratio, mpeak_w, mean_data] = response(file, process,
    directory(process).name);`".

**2) for subject _MM_012_P04_06,_ file _momap_pilot04_51_5_5_1_:**

"Attempted to access `data_sm(0, :);` index must be a positive integer or logical.

Error in response (line 34)
   `if (data_sm(position,:) < mean(data_sm))`

Error in folder_response (line 35)
    `[resp, ons, mpeak, avgpeak, ratio, mpeak_w, mean_data] = response(file, process,
    directory(process).name);`".

Find error files (WAV) [here](https://github.com/davhin/ResponseOnsetTool/files/625403/errors.zip).

**Comment by xstraven** [comment]
Error resulted from wrong assumptions about the average of the file. The error is gone now, but the file still looks odd (nothing to see on plot). Closing this issue since the specific bug is fixed now.
