### ISSUE TITLE
Implement fixed amplitude threshold and maxPeak_width criterion

### ISSUE THREAD

**Issue by reisnerv** [davhin/ResponseOnsetTool#6]
Based on analysis, some balancing of fixed min. amplitude threshold (say, 0.25) and min. maxPeak_width (say, 15ms) should be required to optimize the false positive error rate. Make them adjustable via set_parameters.m.

**Comment by xstraven** [comment]
Now built in:

% Minimal width for the maxpeak
MIN_MAXPEAK_WIDTH = 0.015;

% Threshold for the max peak to be counted as a response
AMP_THRESHOLD = 0.25;

**Comment by xstraven** [comment]
In the future might combine the MEAN_THRESHOLD  (%for the mean amplitude of the file) with the AMP_THRESHOLD.
