### ISSUE TITLE
Wrong record_error classification

### ISSUE THREAD

**Issue by reisnerv** [davhin/ResponseOnsetTool#9]
Issue: False calssification of non-responder ('0') as record_errors ('99') by using the actual Tool version.
 
I tried: adjusting `maxPeak_threshold` value (0.05, 0.005, 0.0005) with `mean_threshold` = 0,001, removing `maxPeak_threshold` and using code from the former version to catch record_errors: `mean_data = mean(data);
if (mean_data < record_error_threshold)
    response = 99;
    onset = 0;
end`.

However, the Bug still persists.

**Comment by xstraven** [comment]
Can you point me to a specific file where this happened, so I can run some analysis?
